version: '3.8'

services:
  db:
    image: postgres:13.7
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${USUARIO_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  pgdata:
